[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
commit_reveal = "ApZkb8Ui4yH3cw86v42uCZnDZb4LUhhyQff6Bagre1Na"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://xolana.xen.network"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
